### ISSUE TITLE
Špatné číslování bodů stanov

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/spolek-dokumenty#1]
Ve stanovách při zápisu spolku máme body označené písmeny, tady v markdownu jsou ale arabská čísla.

**Comment by MikkCZ** [comment]
@MekliCZ mohl by ses na to podívat?

**Comment by vasimi** [comment]
@MikkCZ Nemohl. GitHubí render MarkDownu je jaký je a já s tím nic neudělám, v kódu je to všechno ordered list a teprve při renderu se nějak určí, jak bude vypadat první úroveň, jak druhá... Třeba u mě v desktop editoru to zůstává číslovaný a nijak se to nepřehazuje. Takže s tímhle nic neudělám. :/

**Comment by MikkCZ** [comment]
Při případném dalším zápisu spolku používejme číslování podle markdownu.

> Pokud spolek nemá předsedu ani místopředsedu, zbývající člen rady svolá valnou hromadu a v jejím rámci zajistí ustanovení nové rady. Pro zastupování spolku navenek platí čl. 5, bod j.

Toto je jediné místo (doufám), kde je špatný odkaz.

**Comment by MikkCZ** [comment]
Každopádně nejdříve je potřeba vůbec řešit, co a jak se spolkem. Dávám blocked.
